require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username = 'ubuntu'
  config.ssh.password = '12345'
  config.nfs.functional = false

  config.vm.provider :openstack do |os|
    os.server_name        = 'vagrant_test'
    os.openstack_auth_url = 'http://cloud-main.bitp.kiev.ua:35357/v3'
    os.username           = 'cloud-user1'
    os.password           = 'putarealpasswordhere'
    os.project_name       = 'CloudKPI'
    os.flavor             = 'm1.small'
    os.image              = 'Ubuntu'
    os.identity_api_version = '3'
    os.domain_name = 'default'
    os.floating_ip_pool   = 'public'
    os.networks = 'kpi-private'
  end

  #config.vm.provision "shell", inline: 'echo "$1 : $2" > ~/provision', args: ['IP', '@@ssh_ip@@']


  # http://www.terrarum.net/blog/masterless-puppet-with-vagrant.html
  config.vm.provision 'shell', :inline => <<-SHELL
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    apt-get update
    apt-get install build-essential -y
    apt-get purge -y puppet
    wget https://apt.puppetlabs.com/puppet5-release-xenial.deb
    dpkg -i puppet5-release-xenial.deb
    apt-get update
    apt-get install -y puppet-agent
  SHELL


  config.vm.provision 'puppet' do |puppet|
    puppet.environment_path = 'environments'
    puppet.environment = 'production'
    puppet.module_path = 'modules'
  end

end

