require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.ssh.username = 'ubuntu'
  config.ssh.port = '2727'
  config.nfs.functional = false

  config.vm.provider :openstack do |os|
    os.server_name        = 'vagrant_test'
    os.openstack_auth_url = 'http://cloud-main.bitp.kiev.ua:35357/v3'
    os.username           = 'name'
    os.password           = 'password'
    os.project_name       = 'sysbio'
    os.flavor             = 'm1.small'
    os.image              = 'sysbio.xenial.ubuntu.raw'
    os.identity_api_version = '3'
    os.domain_name = 'default'
    os.floating_ip_pool   = 'public'
    os.networks = 'sysbio-private'
    os.user_data = """#!/bin/bash

      sudo sed -i 's/Port 22/Port 2727/' /etc/ssh/sshd_config
      sudo service ssh restart
    """
  end

  # http://www.terrarum.net/blog/masterless-puppet-with-vagrant.html
  config.vm.provision 'shell', :inline => <<-SHELL
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    apt-get update
    apt-get install build-essential -y
    apt-get purge -y puppet
    wget https://apt.puppetlabs.com/puppet5-release-xenial.deb
    dpkg -i puppet5-release-xenial.deb
    apt-get update
    apt-get install -y puppet-agent
  SHELL

  config.vm.provision 'puppet' do |puppet|
    puppet.environment_path = 'environments'
    puppet.environment = 'production'
    puppet.module_path = 'modules'
  end

end

